[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  port = 8888
  publish = "."
  targetPort = 8888

# Dynamic redirects to forward frontend API calls to Netlify Serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Serverless scheduled cron jobs
[functions."daily-cron"]
  schedule = "30 2 * * *" # Runs daily at 2:30 AM UTC (8:00 AM IST)
